name: Firebase Hosting Deploy

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # or the version you are using

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Firebase Deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Use the Firebase token from your GitHub secrets
      run: firebase deploy --only hosting
